---
services:
  otelcol:
    environment:
      MACKEREL_APIKEY: ${MACKEREL_APIKEY}
    image: otel/opentelemetry-collector-contrib:latest
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "3"
    network_mode: host
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-contrib/config.yaml
